/// 256 words for a device's fingerprint (one per byte): short, distinct and easy to say.
const WORDS: [&str; 256] = [
    "acid", "acorn", "actor", "adult", "agent", "album", "alert", "alien", "alloy", "amber", "anchor", "angle",
    "ankle", "apple", "apron", "arch", "arena", "armor", "arrow", "atlas", "attic", "audio", "autumn", "avocado",
    "axis", "bacon", "badge", "bagel", "baker", "bamboo", "banana", "banjo", "barn", "basil", "basket", "beach",
    "beacon", "beard", "beaver", "bench", "berry", "bike", "bingo", "birch", "bison", "blade", "blanket", "blossom",
    "boat", "bonus", "book", "boot", "bottle", "boulder", "bowl", "brain", "branch", "bread", "brick", "bridge",
    "broom", "bubble", "bucket", "buffalo", "bugle", "cabin", "cable", "cactus", "camel", "camera", "canal", "candle",
    "canoe", "canyon", "carbon", "carpet", "carrot", "castle", "cedar", "cello", "chalk", "cherry", "chess", "chimney",
    "cider", "cinema", "circle", "citrus", "clay", "cliff", "clock", "cloud", "clover", "coast", "cobalt", "cocoa",
    "comet", "copper", "coral", "cotton", "cougar", "crane", "crayon", "cricket", "crystal", "cup", "curtain", "cycle",
    "daisy", "dance", "delta", "desert", "diamond", "dingo", "dolphin", "domino", "donkey", "dragon", "drum", "eagle",
    "easel", "echo", "eclipse", "elbow", "elder", "ember", "emerald", "engine", "falcon", "feather", "fern", "ferry",
    "fiddle", "finch", "flag", "flute", "forest", "fossil", "fountain", "fox", "frost", "galaxy", "garden", "garlic",
    "gecko", "ginger", "glacier", "globe", "goat", "granite", "grape", "gravel", "guitar", "hammer", "harbor", "harp",
    "hazel", "helmet", "heron", "hollow", "honey", "horizon", "igloo", "iris", "island", "ivory", "jacket", "jaguar",
    "jasmine", "jelly", "jungle", "kayak", "kettle", "kiwi", "koala", "ladder", "lagoon", "lantern", "laser", "lemon",
    "lily", "lime", "lizard", "llama", "lobster", "locket", "lotus", "magnet", "mango", "maple", "marble", "meadow",
    "melon", "meteor", "mint", "mirror", "moose", "mosaic", "muffin", "nectar", "needle", "nickel", "noodle", "oasis",
    "ocean", "olive", "onion", "orbit", "orchid", "otter", "oyster", "paddle", "panda", "paper", "parrot", "pasta",
    "peach", "pebble", "pencil", "pepper", "piano", "pickle", "pillow", "pine", "planet", "plum", "pocket", "polar",
    "pony", "poppy", "prism", "pumpkin", "puzzle", "quartz", "quill", "rabbit", "radar", "radish", "raven", "reef",
    "ribbon", "river", "robin", "rocket", "rose", "ruby", "saddle", "salmon", "sandal", "satin", "scarf", "shell",
    "silver", "sketch", "sled", "snail",
];
