#!/bin/sh
# Writes a placeholder engine sidecar for local development:
#   app/src-tauri/binaries/breakpatch-engine-<host-triple>
# It execs `python -m breakpatch_engine` from engine/.venv, so `cargo build` and
# `npm run tauri dev` work without the PyInstaller binary. A real binary written by
# engine/scripts/build_sidecar.sh is never overwritten (pass --force to replace it).
set -eu

MARKER="breakpatch-dev-sidecar-placeholder"
here=$(cd "$(dirname "$0")" && pwd)
app_dir=$(dirname "$here")
engine_dir=$(cd "$app_dir/../engine" && pwd)
bin_dir="$app_dir/src-tauri/binaries"

triple=$(rustc -vV 2>/dev/null | sed -n 's/^host: //p')
if [ -z "$triple" ]; then
  echo "dev-sidecar: rustc not found; install Rust from https://rustup.rs" >&2
  exit 1
fi
target="$bin_dir/breakpatch-engine-$triple"

force=0
for arg in "$@"; do
  case "$arg" in
    --force) force=1 ;;
    *) echo "usage: $0 [--force]" >&2; exit 2 ;;
  esac
done

if [ -e "$target" ] && ! grep -q "$MARKER" "$target" 2>/dev/null && [ "$force" -eq 0 ]; then
  echo "dev-sidecar: $target is a real engine build; leaving it (use --force to replace)."
  exit 0
fi

mkdir -p "$bin_dir"
cat > "$target" <<SCRIPT
#!/bin/sh
# $MARKER (generated by app/scripts/dev-sidecar.sh, not for release)
ENGINE_DIR="$engine_dir"
PY="\$ENGINE_DIR/.venv/bin/python"
if [ ! -x "\$PY" ]; then
  echo "breakpatch-engine (dev): \$PY not found. Create it: cd engine && python3.11 -m venv .venv && .venv/bin/pip install -e '.[dev]'" >&2
  exit 1
fi
exec "\$PY" -m breakpatch_engine "\$@"
SCRIPT
chmod +x "$target"
echo "dev-sidecar: wrote $target"
